# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

orbs:
  tailscale: crowley-namespace/tailscale@1.0.0

# Specify the execution environment. You can specify an image from Docker Hub or use one of our convenience images from CircleCI's Developer Hub.
# See: https://circleci.com/docs/configuration-reference/#executor-job
executors:
  default:
    docker:
      - image: cimg/base:stable

commands:
  echo-command:
    parameters:
      message:
        description: message to be printed
        type: string
        default: ""
      title:
        description: step name
        type: string
        default: job
    steps:
      - run:
          name: << parameters.title >>
          command: |
            echo Say << parameters.message >>!

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/configuration-reference/#jobs
jobs:
  init-job:
    executor: default
    resource_class: small
    # Add steps to the job
    # See: https://circleci.com/docs/configuration-reference/#steps
    steps:
      # - checkout
      - echo-command:
          title: Init
          message: "Init!"

  say-hello:
    executor: default
    resource_class: small
    # Add steps to the job
    # See: https://circleci.com/docs/configuration-reference/#steps
    steps:
      - echo-command:
          title: "Say hello"
          message: "Hello!"

  say-world:
    executor: default
    resource_class: small
    # Add steps to the job
    # See: https://circleci.com/docs/configuration-reference/#steps
    steps:
      - echo-command:
          title: "Say world"
          message: "World!"

  deploy:
    # Specify the execution environment. You can specify an image from Docker Hub or use one of our convenience images from CircleCI's Developer Hub.
    # See: https://circleci.com/docs/configuration-reference/#executor-job
    executor: default
    resource_class: small
    steps:
      - echo-command:
          title: "Deploy"
          message: "Deploy!"

  use-tailscale:
    # Specify the execution environment. You can specify an image from Docker Hub or use one of our convenience images from CircleCI's Developer Hub.
    # See: https://circleci.com/docs/configuration-reference/#executor-job
    executor: default
    resource_class: small
    steps:
      - tailscale/install
      - run:
          name: x
          command: |
            sudo -E tailscaled --state=mem: --tun=userspace-networking 2>~/tailscaled.log &
            # And check that tailscaled came up. The CLI will block for a bit waiting
            # for it. And --json will make it exit with status 0 even if we're logged
            # out (as we will be). Without --json it returns an error if we're not up.
            sudo -E tailscale status --json >/dev/null
            ps -aux
          background: true
      - tailscale/connect:
          tailscale-optional-flags: --advertise-tags=tag:ci --hostname=$(echo circleci-${HOSTNAME}) --accept-routes
      - echo-command:
          title: "Demo"
          message: "Demo!"
      - run:
          name: connectivity
          command: |
            nc -w 3 ${ENDPOINT} 22
      - tailscale/disconnect

# Orchestrate jobs using workflows
# See: https://circleci.com/docs/configuration-reference/#workflows
workflows:
  tagged-build:
    jobs:
      - init-job:
          filters:
            tags:
              ignore: /^v.*-test.*/
            branches:
              ignore: /.*/
      - use-tailscale:
          requires:
            - init-job

  tagged-test-build:
    jobs:
      - init-job:
          filters:
            tags:
              only: /^v.*-test.*/
            branches:
              ignore: /.*/
      - use-tailscale:
          filters:
            tags:
              only: /^v.*-test.*/
            branches:
              ignore: /.*/
          requires:
            - init-job

  say-hello-workflow:
    jobs:
      - init-job:
          filters:
            branches:
              only: main
            tags:
              ignore: /.*/
      - say-hello:
          requires:
            - init-job
      - say-world:
          requires:
            - init-job
      - hold:
          type: approval
          requires:
            - say-hello
            - say-world
      - deploy:
          requires:
            - hold
